# Generated by Django 4.0 on 2021-12-14 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AIN-1-21', 'AIN-1-21'), ('AIN-2-21', 'AIN-2-21'), ('AIN-3-21', 'AIN-3-21'), ('WIN-1-21', 'WIN-1-21'), ('MIN-1-21', 'MIN-1-21'), ('AIN-1-20', 'AIN-1-20'), ('AIN-2-20', 'AIN-2-20'), ('AIN-3-20', 'AIN-3-20'), ('WIN-1-20', 'WIN-1-20'), ('MIN-1-20', 'MIN-1-20'), ('AIN-1-19', 'AIN-1-19'), ('AIN-2-19', 'AIN-2-19'), ('AIN-3-19', 'AIN-3-19'), ('WIN-1-19', 'WIN-1-19'), ('MIN-1-19', 'MIN-1-19'), ('AIN-1-18', 'AIN-1-18'), ('AIN-2-18', 'AIN-2-18'), ('AIN-3-18', 'AIN-3-18'), ('WIN-1-18', 'WIN-1-18'), ('MIN-1-18', 'MIN-1-18'), ('admin', 'admin')], max_length=15)),
                ('size', models.IntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('501', '501'), ('502', '502')], max_length=15)),
                ('size', models.IntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='shedule.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='shedule.course')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='shedule.group')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='shedule.professor')),
            ],
        ),
    ]
